swiftlint_version: 0.55.1

included:
  - Sources

disabled_rules:
  - inclusive_language
  - large_tuple
  - nsobject_prefer_isequal
  - operator_whitespace

opt_in_rules:
  - anonymous_argument_in_multiline_closure
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_objc_type
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nimble_operator
  - no_fallthrough_only
  - nslocalizedstring_key
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_subject
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - xct_specific_matcher
  - yoda_condition

closure_body_length:
  warning: 80
cyclomatic_complexity:
  ignores_case_statements: true
deployment_target:
  iOS_deployment_target: 14.0
empty_count:
  severity: warning
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  Copyright © \d{4} Westerra CU\. All rights reserved\.
                    \/\/
function_body_length:
  warning: 75
line_length:
  warning: 175
  ignores_comments: true
shorthand_operator:
  severity: warning
statement_position:
  statement_mode: uncuddled_else
switch_case_alignment:
  indented_cases: false
trailing_closure:
  only_single_muted_parameter: true
vertical_whitespace:
  max_empty_lines: 2

##################################
# Rules to consider enabling (Needs Discussion):
#  - balanced_xctest_lifecycle
#  - discarded_notification_center_observer
#  - file_types_order
#  - required_enum_case (Discuss for awareness down the road)
#  - type_contents_order
##################################


##################################
## Experimental Analyzer
##################################

analyzer_rules:
  - capture_variable
  - unused_declaration
  - unused_import

# Rules we will not opt in to
# - explicit_self
